services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=life-med
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backup:/backup
    ports:
      - "5443:5432"
    container_name: life-med